
package com.test.cxf.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import com.test.cxf.service.impl.ServiceImplService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2017-08-14T16:02:05.758+08:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
public final class IService_ServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.service.cxf.test.com/", "ServiceImplService");

    private IService_ServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ServiceImplService ss = new ServiceImplService(wsdlURL, SERVICE_NAME);
        IService port = ss.getServiceImplPort();  
        
        {
        System.out.println("Invoking get...");
        java.lang.String _get_id = "";
        java.lang.String _get__return = port.get(_get_id);
        System.out.println("get.result=" + _get__return);


        }

        System.exit(0);
    }

}
